function cssSlug(str) {
  if (!str) return "";
  return String(str)
    .toLowerCase()
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

function csvField(val) {
  const s = String(val !== undefined && val !== null ? val : "");
  return s.includes(",") || s.includes('"') || s.includes("\n") ? `"${s.replace(/"/g, '""')}"` : s;
}

const ExportFormatter = {
  // ── CSV ─────────────────────────────────────────────────────────────────────
  toCSV(result, config) {
    const lines = [];

    // Section 1: color ramps
    lines.push("COLOR RAMPS");
    lines.push("Group,Weight,Hex,Light Contrast,Light Rating,Dark Contrast,Dark Rating");
    for (const [colorName, ramp] of Object.entries(result.colorRamps)) {
      for (const [weightName, entry] of Object.entries(ramp)) {
        lines.push([csvField(colorName), csvField(weightName), csvField(entry.value), csvField(entry.contrast.light.ratio), csvField(entry.contrast.light.rating), csvField(entry.contrast.dark.ratio), csvField(entry.contrast.dark.rating)].join(","));
      }
    }

    // Section 2: Role tokens (both themes)
    lines.push("");
    lines.push("ROLE TOKENS");
    lines.push("Color,Role,Variation,Theme,Hex,Contrast,Rating,Adjusted");
    for (const theme of ["light", "dark"]) {
      if (!result.colorTokens || !result.colorTokens[theme]) continue;
      for (const [colorName, roles] of Object.entries(result.colorTokens[theme])) {
        for (const [roleId, variations] of Object.entries(roles)) {
          const roleName = (config.roles[roleId] && config.roles[roleId].name) || roleId;
          for (let i = 0; i < config.variations.length; i++) {
            const token = variations[String(i)];
            if (!token) continue;
            const dispName = config.variations[i].shorthand || config.variations[i].name;
            lines.push([csvField(colorName), csvField(roleName), csvField(dispName), csvField(theme), csvField(token.value), csvField(token.contrast ? token.contrast.ratio : ""), csvField(token.contrast ? token.contrast.rating : ""), csvField(token.isAdjusted ? "yes" : "")].join(","));
          }
        }
      }
    }

    return lines.join("\n");
  },

  // ── CSS ─────────────────────────────────────────────────────────────────────
  // Three sections: :root color ramps, [data-theme] semantic tokens, @media OS dark fallback.
  toCSS(result, config) {
    const date = new Date().toISOString();
    let css = `/* ${config.name} — generated by ctm316 | ${date} */\n\n`;

    // Color ramps in :root
    css += `:root {\n  /* ── Color Ramps ── */\n`;
    for (const [colorName, ramp] of Object.entries(result.colorRamps)) {
      css += `\n  /* ${colorName} */\n`;
      for (const [weightName, entry] of Object.entries(ramp)) {
        css += `  --${cssSlug(colorName)}-${cssSlug(String(weightName))}: ${entry.value};\n`;
      }
    }
    css += `}\n`;

    // Semantic tokens per theme
    for (const theme of ["light", "dark"]) {
      if (!result.colorTokens || !result.colorTokens[theme]) continue;
      const selector = theme === "light" ? `:root,\n[data-theme="light"]` : `[data-theme="dark"]`;
      css += `\n/* ── ${theme.toUpperCase()} Semantic Tokens ── */\n${selector} {\n`;
      for (const [colorName, roles] of Object.entries(result.colorTokens[theme])) {
        css += `\n  /* ${colorName} */\n`;
        for (const [roleId, variations] of Object.entries(roles)) {
          const roleName = (config.roles[roleId] && config.roles[roleId].name) || roleId;
          for (let i = 0; i < config.variations.length; i++) {
            const token = variations[String(i)];
            if (!token) continue;
            const dispName = config.variations[i].shorthand || config.variations[i].name;
            css += `  --${cssSlug(colorName)}-${cssSlug(roleName)}-${cssSlug(dispName)}: ${token.value};\n`;
          }
        }
      }
      css += `}\n`;
    }

    // OS-level dark mode fallback (only when no data-theme attribute is set)
    if (result.colorTokens && result.colorTokens.dark) {
      css += `\n/* ── OS Dark Mode Fallback ── */\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n`;
      for (const [colorName, roles] of Object.entries(result.colorTokens.dark)) {
        for (const [roleId, variations] of Object.entries(roles)) {
          const roleName = (config.roles[roleId] && config.roles[roleId].name) || roleId;
          for (let i = 0; i < config.variations.length; i++) {
            const token = variations[String(i)];
            if (!token) continue;
            const dispName = config.variations[i].shorthand || config.variations[i].name;
            css += `    --${cssSlug(colorName)}-${cssSlug(roleName)}-${cssSlug(dispName)}: ${token.value};\n`;
          }
        }
      }
      css += `  }\n}\n`;
    }

    return css;
  },
};

// ── SCSS EXPORT ──────────────────────────────────────────────────────────────
// Produces proper SCSS: flat ramp variables, per-color nested maps,
// token maps per theme, an apply-theme mixin, and theme selectors.
function scssSlug(str) {
  return cssSlug(str); // reuse the same sanitiser
}

function generateScss(result, config) {
  if (!result || !result.colorRamps) return "";
  const configVariations = (config && config.variations) || [];
  const systemName = (config && config.name) || "tokens";
  const date = new Date().toISOString();

  const hr = (title) => `// ${"=".repeat(58)}\n// ${title}\n// ${"=".repeat(58)}\n\n`;

  let scss = `// ${systemName} — Auto-generated SCSS\n// Generated: ${date}\n// Do not edit manually.\n\n`;
  scss += `@use 'sass:map';\n\n`;

  // ── 1. Flat ramp variables ($primary-1, $primary-2 …)
  scss += hr("COLOR RAMP VARIABLES");
  for (const [group, weights] of Object.entries(result.colorRamps)) {
    scss += `// ${group}\n`;
    for (const [weight, data] of Object.entries(weights)) {
      if (!data || !data.value) continue;
      scss += `$${scssSlug(group)}-${scssSlug(String(weight))}: ${data.value};\n`;
    }
    scss += "\n";
  }

  // ── 2. Per-color nested maps (for programmatic access via map.get)
  scss += hr("PER-COLOR RAMP MAPS");
  for (const [group, weights] of Object.entries(result.colorRamps)) {
    scss += `$ramp-${scssSlug(group)}: (\n`;
    for (const [weight, data] of Object.entries(weights)) {
      if (!data || !data.value) continue;
      scss += `  ${scssSlug(String(weight))}: $${scssSlug(group)}-${scssSlug(String(weight))},\n`;
    }
    scss += `);\n\n`;
  }

  // ── 3. Token maps per theme (values reference the flat ramp variables)
  for (const theme of ["light", "dark"]) {
    if (!result.colorTokens || !result.colorTokens[theme]) continue;
    scss += hr(`${theme.toUpperCase()} THEME TOKENS`);
    scss += `$tokens-${theme}: (\n`;
    for (const [colorName, roles] of Object.entries(result.colorTokens[theme])) {
      scss += `  // ${colorName}\n`;
      for (const [roleId, variations] of Object.entries(roles)) {
        const roleName = (config && config.roles[roleId] && config.roles[roleId].name) || roleId;
        for (let i = 0; i < configVariations.length; i++) {
          const token = variations[String(i)];
          if (!token || !token.tknRef) continue;
          const dispName = configVariations[i].shorthand || configVariations[i].name;
          const tokenKey = `${scssSlug(colorName)}-${scssSlug(roleName)}-${scssSlug(dispName)}`;
          // tknRef is "colorName-weight" (e.g. "Primary-18") — split on last dash
          const lastDash = token.tknRef.lastIndexOf("-");
          const refGroup = scssSlug(token.tknRef.substring(0, lastDash));
          const refWeight = scssSlug(token.tknRef.substring(lastDash + 1));
          const adjusted = token.isAdjusted ? " /* ⚠ adjusted */" : "";
          scss += `  "${tokenKey}": $${refGroup}-${refWeight},${adjusted}\n`;
        }
      }
    }
    scss += `);\n\n`;
  }

  // ── 4. apply-theme mixin
  scss += hr("THEME MIXIN");
  scss += `/// Writes all token map entries as CSS custom properties.\n`;
  scss += `/// Usage: @include apply-theme($tokens-light);\n`;
  scss += `@mixin apply-theme($tokens) {\n`;
  scss += `  @each $name, $value in $tokens {\n`;
  scss += `    --#{$name}: #{$value};\n`;
  scss += `  }\n`;
  scss += `}\n\n`;

  // ── 5. Theme output
  scss += hr("THEME OUTPUT");
  scss += `// Class-based theming\n`;
  scss += `:root,\n[data-theme="light"] {\n  @include apply-theme($tokens-light);\n}\n\n`;
  scss += `[data-theme="dark"] {\n  @include apply-theme($tokens-dark);\n}\n\n`;
  scss += `// OS-level dark mode fallback\n`;
  scss += `@media (prefers-color-scheme: dark) {\n`;
  scss += `  :root:not([data-theme]) {\n`;
  scss += `    @include apply-theme($tokens-dark);\n`;
  scss += `  }\n`;
  scss += `}\n`;

  return scss;
}
